name: My workflow
on:
  pull_request: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print on first job
        run: |
          echo "The run number in first job is: ${{ github.run_number }}"

  clayton:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Change directory to project directory
        run: |
          cd /home/runner/work/test_github_actions/
      - name: List files in directory
        run: |
          ls      
      - name: Create tag
        run: |
          pwd
          git tag 1.0.${{ github.run_number }}


