name: My workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print on first job
        run: |
          echo "The run number in first job is: ${{ github.run_number }}""
  clayton:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print in second job
        run: |
          echo "The run number in second job is: ${{ github.run_number }}"

  narutin:
    runs-on: ubuntu-latest
    needs: clayton
