name: ci-pr
on:
  pull_request:
jobs:
  create-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run tag
        run: |
          git tag 1.0.${{ github.run_number }}
          git push origin 1.0.${{ github.run_number }}


