name: My workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print on first job
        run: |
          echo "The run number in first job is: ${{ github.run_number }}"

  clayton:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create tag
        run: |
          git tag "1.0.${{ github.run_number }}"

