name: My workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Store the run number in a variable
        run: |
          echo "The run number in first step is: ${{ github.run_number }}"
      - name: Print the run number
        shell: /usr/bin/bash -e {0}
        run: |
          echo "The run number in second step is: ${{ github.run_number }}"