name: ci-pr
on:
  pull_request:
    branches: 
      - main
jobs:
  create-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run tag
        run: |
          git tag ${{ github.head_ref }} 1.0.${{ github.run_number }}
          git push origin ${{ github.head_ref }} 1.0.${{ github.run_number }}
