name: My workflow
on:
  pull_request: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print on first job
        run: |
          echo "The run number in first job is: ${{ github.run_number }}"

  clayton:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Print current directory
        run: |
          cd ..           
          pwd   
          ls 
      - name: Create tag
        run: |
          cd ..
          pwd
          ls 
          git tag 1.0.${{ github.run_number }}


